channels:
    - pytorch
    - conda-forge
name: cvblock
dependencies:
    - pytorch-gpu
    - torchvision
    - cudatoolkit=10.1
    - imageio
    - scikit-learn
    - scikit-image
    - tqdm

# required too : conda install pip
# ~/anaconda3/envs/<env-name>/bin/pip install cifar2png
# ~/anaconda3/envs/<env-name/bin/pip install tensorboard
# ~/anaconda3/envs/<env-name/bin/pip install tb-nightly
