# -*- coding: utf-8 -*-
"""Kopie von 3_multi_layer_perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sJqF7pXGFi635cIKMlz2GPOuSy_eDRDe

<a href="https://colab.research.google.com/github/constantinpape/training-deep-learning-models-for-vison/blob/master/day1/3_multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multi-layer Perceptron on CIFAR10

Based on the previous exercise, we will train a multi-layer network, also known as multi-layer perceptron. In this architecture, we will have 'hidden layers', i.e. layers that receive input not from the input directly but from previous layers in the network and that are not directly observed in the output.

## Preperation
"""

# Commented out IPython magic to ensure Python compatibility.
# load tensorboard extension # Marcos Carbonell version
# %load_ext tensorboard

# import torch and other libraries
import os
import matplotlib.pyplot as plt
import sys
sys.path.append(os.path.abspath('utils'))
import numpy as np
import sklearn
from tqdm import trange
from mlp import MLP
from mlp_sigmoid import MLP_Sigmoid
from mlp_more_layers import MLP_More_Layers
import tqdm
import torch

# check if we have gpu support
# colab offers free gpus, however they are not activated by default.
# to activate the gpu, go to 'Runtime->Change runtime type'. 
# Then select 'GPU' in 'Hardware accelerator' and click 'Save'
have_gpu = torch.cuda.is_available()
# we need to define the device for torch, yadda yadda
if have_gpu:
    print("GPU is available")
    device = torch.device('cuda')
else:
    print("GPU is not available, training will run on the CPU")
    device = torch.device('cpu')

# run this in google colab to get the utils.py file

# we will reuse the training function, validation function and
# data preparation from the previous notebook
import utils

cifar_dir = './cifar10'

categories = os.listdir('./cifar10/train')
categories.sort()

"""## Multi-layer perceptron

In this execise, we go from a single layer network to a network with multiple layers, also known as multi-layer perceptron, or MLP.
We still use fully connected layers (`nn.Linear`), i.e. each neuron in a given layer receives input from all neurons in the previous layer.

Imporantly, we apply a non-linearity to all layer outputs.
Otherwise, the layers could be collapsed into a single layer by matrix multiplication.
"""

# instantiate the model
model = MLP(3072, 10)
model.to(device)

# get training and validation data
train_dataset, val_dataset = utils.make_cifar_datasets(cifar_dir)

# Commented out IPython magic to ensure Python compatibility.
# instantiate loaders, loss, optimizer and tensorboard

train_loader =  torch.utils.data.DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader =    torch.utils.data.DataLoader(val_dataset, batch_size=25)

optimizer = torch.optim.Adam(model.parameters(), lr=1.e-3)

loss_function = torch.nn.NLLLoss()
loss_function.to(device)

tb_logger = torch.utils.tensorboard.SummaryWriter('runs/log_mlp')
# %tensorboard --logdir runs

# train for a couple of epochs
n_epochs = 4
for epoch in trange(n_epochs):
    utils.train(model, train_loader, loss_function, optimizer,
                device, epoch, tb_logger=tb_logger)
    step = (epoch + 1) * len(train_loader)
    utils.validate(model, val_loader, loss_function,
                   device, step,
                   tb_logger=tb_logger)

# evaluate the model on test data
test_dataset = utils.make_cifar_test_dataset(cifar_dir)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=25)
predictions, labels = utils.validate(model, test_loader, loss_function,
                                     device, step=0, tb_logger=None)

print("Test accuracy:")
accuracy = sklearn.metrics.accuracy_score(labels, predictions)
print(accuracy)

fig, ax = plt.subplots(1, figsize=(8, 8))
utils.make_confusion_matrix(labels, predictions, categories, ax)
# 3 different learning rates

"""## Tasks and Questions

Tasks
- Try 3 different learning rate values and observe how this changes the training curves, training time and results on the test data.
- Try different architectures for your MLP. For example, you can increase the number of layers or use a different activation function (e.g. Sigmoid) and compare them on the test dataset.

Question:
- Which of the models you have trained in this and in the previous notebook perform best?
- Besides the final performance, how do the training curves differ?
- Can you find any systematic similarities or differences in the confusion matrix for the different models?
- What can you do to make the results of these comparisons more reliable?

Advanced:
- Try one or more of your architectures with preset filters (see last notebook) as input features.
"""

plt.show()
